Feature/admin
stasya-k/task-manager pull request #11
Opened 2021-12-01 10:16 UTC by stasya-k

2021-12-01 16:13 UTC, greybutton requested changes
добавь .devcontainer в гитигнор, это файлы для локальной разработки

2021-12-01 16:13 UTC, greybutton commented on app/views/layouts/application.html.slim
> +              = link_to "Log out", session_path, method: "delete", confirm: "confirm?", class: 'mdl-navigation__link'
логаут всем доступен, не только админу

2021-12-02 10:11 UTC, stasya-k commented on app/views/layouts/application.html.slim
> +              = link_to "Log out", session_path, method: "delete", confirm: "confirm?", class: 'mdl-navigation__link'
> добавь .devcontainer в гитигнор, это файлы для локальной разработки

странно, добавляла изначально, но что-то пошло не так.

> 

Исправила

2021-12-02 17:07 UTC, greybutton approved these changes

2021-12-03 13:00 UTC, merged