feature/kanban board
stasya-k/task-manager pull request #14
Opened 2021-12-11 10:01 UTC by stasya-k

2021-12-11 19:47 UTC, greybutton requested changes

2021-12-11 19:47 UTC, greybutton commented on app/javascript/packs/application.js
> +import WebpackerReact from 'webpacker-react';
не вижу добавленного гема

2021-12-12 07:16 UTC, stasya-k commented on app/javascript/packs/application.js
> +import WebpackerReact from 'webpacker-react';
добавила

2021-12-12 16:51 UTC, greybutton requested changes

2021-12-12 16:51 UTC, greybutton commented on Gemfile
> +gem 'webpacker-react', "~> 1.0.0.beta.1"
поставь плис 0.3.2, с бетой проблемы могут быть

2021-12-12 16:51 UTC, greybutton commented on package.json
> +    "@asseinfo/react-kanban": "^2.2.0",
styled-components не потребовался?

2021-12-13 08:31 UTC, stasya-k commented on Gemfile
> +gem 'webpacker-react', "~> 1.0.0.beta.1"
Исправила. Увидела, что по доке версии в package.json и Gemfile должны соответствовать.

2021-12-13 08:35 UTC, stasya-k commented on package.json
> +    "@asseinfo/react-kanban": "^2.2.0",
Нет, я так понимаю, он и не нужен. По крайней мере в этом уроке.

2021-12-13 18:04 UTC, greybutton approved these changes

2021-12-13 21:01 UTC, merged