feature/associations and validations
stasya-k/task-manager pull request #5
Opened 2021-11-22 19:25 UTC by stasya-k

2021-11-22 20:16 UTC, greybutton requested changes

2021-11-22 20:16 UTC, greybutton commented on app/models/user.rb
> +  validates :last_name, presence: true
не хватает одной валидации
> Имя и фамилия не могут быть меньше двух букв.

2021-11-23 07:34 UTC, stasya-k commented on app/models/user.rb
> +  validates :last_name, presence: true
fixed

Насколько правильно было бы использовать такую запись? Учитывая, что валидация полностью идентична:

`validates :last_name, :first_name, presence: true, length: { minimum: 2 }`

2021-11-23 10:09 UTC, greybutton commented on app/models/user.rb
> +  validates :last_name, presence: true
такая запись тоже правильная, больше зависит от предпочтений программиста в одну или две строчки сделать

2021-11-23 10:10 UTC, greybutton approved these changes

2021-11-23 11:07 UTC, merged