add state machine
stasya-k/task-manager pull request #6
Opened 2021-11-23 15:49 UTC by stasya-k

2021-11-23 18:56 UTC, greybutton requested changes

2021-11-23 18:56 UTC, greybutton commented on app/models/task.rb
> +    event :to_archive do
Как-то странно называются события. В данном случае должен использовать глагол, который описывает переход. Ивент это функция, название функции - глагол

2021-11-24 08:58 UTC, stasya-k commented on app/models/task.rb
> +    event :to_archive do
fixed

2021-11-24 19:06 UTC, greybutton approved these changes

2021-11-24 20:57 UTC, merged